Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-21.04"

  config.vm.define "m1" do |m1|
     m1.vm.hostname  = "jenkins"
	 m1.vm.network "private_network", ip: "172.32.0.21"
	 m1.vm.provider "virtualbox" do |vb|
	   vb.name = "jenkins"
	 end
	end
	config.vm.provision "shell" ,path: "jenkins.sh"
  end